compile: models/*.java view/*.java controller/*.java Main.java
	javac models/*.java view/*.java controller/*.java Main.java

run: Main.class
	java Main

clean:
	rm -f models/*class
	rm -f view/*.class
	rm -f controller/*.class
	rm -f *.class